[build]
  base    = ""
  publish = "website/build"
  command = "yarn && yarn build"

[context.production.environment]
  NODE_VERSION = "16.15.0"
  NODE_OPTIONS = "--max_old_space_size=4096"

[context.deploy-preview.environment]
  NODE_VERSION = "16.15.0"
  NODE_OPTIONS = "--max_old_space_size=4096"
  PREVIEW_DEPLOY = "true"